#!/bin/sh
# Rename a command.

# Parameters are sent with -o "oldname" -n "newname".

# Load options:
while getopts ":o:n:" O; do
 case $O in
  o)
   OLDNAME=`echo $OPTARG | sed s/'"'//g`
   ;;
  n)
   NEWNAME=`echo $OPTARG | sed s/'"'//g`
   ;;
 esac
done

cat - | \
 xmlstarlet ed -u "/geogebra/construction/command[@name=\"$OLDNAME\"]/@name" -v "$NEWNAME"
